sudo: required

language: scala
scala:
   - 2.11.7
jdk:
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION test updateImpactSubmit

services:
  - docker
before_install:
  - docker pull mattermost/platform:2.0
  - docker run -d -p 8080:80 mattermost/platform:2.0
  - docker ps -a
